<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="11" passed="5" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-05T12:51:45 IST" name="Suite" finished-at="2024-09-05T12:52:39 IST" duration-ms="53927">
    <groups>
    </groups>
    <test started-at="2024-09-05T12:51:45 IST" name="Submit Order Test" finished-at="2024-09-05T12:52:39 IST" duration-ms="53927">
      <class name="PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:51:45 IST" name="launchApplication" finished-at="2024-09-05T12:51:49 IST" duration-ms="4243" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="FailBlankLogin()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:51:49 IST" name="FailBlankLogin" finished-at="2024-09-05T12:51:50 IST" duration-ms="552" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [*Email is required] but found [*Email required]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [*Email is required] but found [*Email required]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test.FailBlankLogin(submitOrderCompleteParallelAndReport_Test.java:100)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FailBlankLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:51:50 IST" name="tearDown" finished-at="2024-09-05T12:51:50 IST" duration-ms="727" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:51:50 IST" name="launchApplication" finished-at="2024-09-05T12:51:55 IST" duration-ms="4291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="FailBlankLogin()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:51:55 IST" name="FailBlankLogin" finished-at="2024-09-05T12:51:55 IST" duration-ms="495" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [*Email is required] but found [*Email required]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [*Email is required] but found [*Email required]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test.FailBlankLogin(submitOrderCompleteParallelAndReport_Test.java:100)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FailBlankLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:51:56 IST" name="tearDown" finished-at="2024-09-05T12:51:56 IST" duration-ms="449" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:51:56 IST" name="launchApplication" finished-at="2024-09-05T12:51:59 IST" duration-ms="3073" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:51:59 IST" name="LoginErrorValidation" finished-at="2024-09-05T12:52:00 IST" duration-ms="1134" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:00 IST" name="tearDown" finished-at="2024-09-05T12:52:01 IST" duration-ms="489" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:01 IST" name="launchApplication" finished-at="2024-09-05T12:52:04 IST" duration-ms="2970" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:04 IST" name="submitOrder" data-provider="getData" finished-at="2024-09-05T12:52:09 IST" duration-ms="4653" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{product=ZARA COAT 3, pass=Avishi11, email=anvit@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:09 IST" name="tearDown" finished-at="2024-09-05T12:52:10 IST" duration-ms="784" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:10 IST" name="launchApplication" finished-at="2024-09-05T12:52:13 IST" duration-ms="3858" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:13 IST" name="submitOrder" data-provider="getData" finished-at="2024-09-05T12:52:18 IST" duration-ms="4386" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{product=ADIDAS ORIGINAL, pass=Iamking@000, email=shetty@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:18 IST" name="tearDown" finished-at="2024-09-05T12:52:19 IST" duration-ms="934" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:19 IST" name="launchApplication" finished-at="2024-09-05T12:52:23 IST" duration-ms="3811" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="BlankLogin()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:23 IST" name="BlankLogin" finished-at="2024-09-05T12:52:23 IST" duration-ms="433" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BlankLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:23 IST" name="tearDown" finished-at="2024-09-05T12:52:24 IST" duration-ms="660" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:24 IST" name="launchApplication" finished-at="2024-09-05T12:52:26 IST" duration-ms="2505" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="InvalidLoginErrorValidation()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:26 IST" name="InvalidLoginErrorValidation" finished-at="2024-09-05T12:52:27 IST" duration-ms="1108" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [Logged IN]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [Logged IN]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test.InvalidLoginErrorValidation(submitOrderCompleteParallelAndReport_Test.java:91)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidLoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:27 IST" name="tearDown" finished-at="2024-09-05T12:52:28 IST" duration-ms="645" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:28 IST" name="launchApplication" finished-at="2024-09-05T12:52:31 IST" duration-ms="2846" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="InvalidLoginErrorValidation()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:31 IST" name="InvalidLoginErrorValidation" finished-at="2024-09-05T12:52:32 IST" duration-ms="1092" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Logged IN]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Logged IN]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test.InvalidLoginErrorValidation(submitOrderCompleteParallelAndReport_Test.java:91)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidLoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:32 IST" name="tearDown" finished-at="2024-09-05T12:52:33 IST" duration-ms="385" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:33 IST" name="launchApplication" finished-at="2024-09-05T12:52:36 IST" duration-ms="3430" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:36 IST" name="OrderHistoryTest" finished-at="2024-09-05T12:52:38 IST" depends-on-methods="PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test.submitOrder" duration-ms="1758" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test@1f3f02ee]" started-at="2024-09-05T12:52:38 IST" name="tearDown" finished-at="2024-09-05T12:52:39 IST" duration-ms="735" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
